name: 'build'

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master
